# Generated by Django 3.2.4 on 2021-06-11 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=200)),
                ('stud_id', models.FloatField()),
                ('desc', models.TextField()),
                ('cgpa', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ('stud_id',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('link', models.CharField(max_length=500)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.profile')),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='portfolio.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=150)),
                ('desc', models.TextField()),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='portfolio.profile')),
            ],
        ),
    ]
